### PR TITLE
Change Affine3d to Isometry3d #26

### PR DESCRIPTION
**Pull request by JeroenDM**

### CODE REVIEW

**Comment by JeroenDM** [comment]
See issue #26

**Comment by JeroenDM** [comment]
@simonschmeisser Does this break something in your use case?

**Review by simonschmeisser — APPROVED** [review]
Looks good, this is all internal API  so it shouldn't matter compatibility wise

**Comment by JeroenDM** [comment]
Ah, right, I forgot `getAllIK` is internal.

**Pull request merged**
