### PR TITLE
remove dependency on moveit-ros-planning

### PR DESCRIPTION
**Pull request by simonschmeisser**
seems leftover

### CODE REVIEW

**Comment by JeroenDM** [comment]
Thank you for cleaning that!

**Comment by JeroenDM** [comment]
Mmm, maybe I merged it to quickly... (#unrelated deadline stress...)
Do we need [this](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/pull/34/files#diff-34ae68f4adad56c25c5bc05dcb64794eL66) dependency? @simonschmeisser 
```xml
<exec_depend>moveit_ros_planning</exec_depend>
```

**Comment by simonschmeisser** [comment]
travis should tell us :) (I wonder why there is no checkmark in this PR?)

**Comment by simonschmeisser** [comment]
also there is nothing to be executed in this repo right? <test_depend> could be possible but then still travis should fail

**Comment by JeroenDM** [comment]
> travis should tell us :) (I wonder why there is no checkmark in this PR?)

Mmm, apparently Travis [was failing](https://travis-ci.org/JeroenDM/moveit_opw_kinematics_plugin/branches) without telling us.

> also there is nothing to be executed in this repo right? <test_depend> could be possible but then still travis should fail

I was thinking about the tests indeed.

**Comment by JeroenDM** [comment]
If this is not too urgent for you I will look at this later, as I do not have a lot of spare time this week.

**Comment by simonschmeisser** [comment]
No, that's not important at all, I was just experimenting at home and had not installed the whole MoveIt

Focus on your deadline (final?), I'll update the checks as well (or whatever is required)

**Comment by JeroenDM** [comment]
Thanks.
>  (final?)

It's not that bad (yet) :) just IROS.

**Comment by simonschmeisser** [comment]
Hmm, looks like I screwed that up ... can you revert the merge? To my defense I have to say that moveit-planning is named a bit misleading ...

**Comment by JeroenDM** [comment]
I should not have merged before checking the test results, my bad.

In summary:

- The tests use the `rdf_loader` from `moveit-ros-planning`, so leaving it as a test dependency should fix it?
- This pull request is not relevant to the kinetic branch.
- This one time I did not look at the test results before merging, lesson learned :)

I still can't find why Travis did not show up here in the pull request. Need some more googling.

**Comment by JeroenDM** [comment]
Unrelated side note: too bad all the [compiler warnings](https://github.com/ros-planning/moveit/pull/1773) are not silenced on the melodic branch of MoveIt. `robot_state.h` generates a lot of noise. Unless I'm missing something that can avoid this here.

**Pull request merged**
