### PR TITLE
Change moveit_resources to more specific version for fanuc robot

### PR DESCRIPTION
**Pull request by JeroenDM**

### CODE REVIEW

**Comment by JeroenDM** [comment]
Hmmm, the moveit repo was being built on my Travis account, and now I'm out of credit to build this one :(

**Review by simonschmeisser — APPROVED** [review]
looks good, maybe you could try to trigger another build? There's also a button somewhere for that :-)

**Comment by JeroenDM** [comment]
It seems this pull request was build successfully on the old `.org` domain of Travis [here](https://travis-ci.org/github/JeroenDM/moveit_opw_kinematics_plugin). So I'll merge this.

On the new `.com` version my account is still disabled because it started building everything by default I think. But I'm not sure how the notifications with Github work with these two domains being active.

**Comment by JeroenDM** [comment]
@simonschmeisser Thank you for the review and the reminder!

**Pull request merged**
