### PR TITLE
Use logname var instead of the inline string "opw" everywhere

### PR DESCRIPTION
**Pull request by JeroenDM**
First merge https://github.com/JeroenDM/moveit_opw_kinematics_plugin/pull/76 and rebase.

### CODE REVIEW

**Comment by JeroenDM** [comment]
I also tested this locally to circumvent CI not fixed yet in this branch.

**Comment by JeroenDM** [comment]
(Looking forward to the day we can compile with c++20 and make `LOGNAME` and `std::string` again, but that's just nitpicking I guess :) )

**Comment by simonschmeisser** [comment]
I had a quick glance at MoveIt PlanningScene and there it is `const std::string LOGNAME`, is there a real difference between either of them?

**Comment by JeroenDM** [comment]
> I had a quick glance at MoveIt PlanningScene and there it is const std::string LOGNAME, is there a real difference between either of them?

Not really, I once got it as a review comment to use constexpr and therefore updated the docs:
https://github.com/ros-planning/moveit.ros.org/pull/474.

But in hindsight it's a clear example of me taking nitpicking too far... :) I guess in general C++ programmers have a tendency to over optimize.

**Comment by simonschmeisser** [comment]
> I guess in general C++ programmers have a tendency to over optimize.

Agreed. Seriously, I don't actually want to know the difference and I hope the compiler does it's job and the end result is just the same ...

**Pull request merged**
