### PR TITLE
Port to ROS2

### PR DESCRIPTION
**Pull request by JeroenDM**
#73

### CODE REVIEW

**Comment by JeroenDM** [comment]
Ok, this is more involved than I thought. It will take more than one World MoveIt day to finish.

**Comment by RoboticsYY** [comment]
@JeroenDM Can I ask the status of this effort and how it will proceed? If no one is taking it, anything we can contribute to?

**Comment by JeroenDM** [comment]
I did not continue on this or plan to in the near future, sorry. Feel free to open a new pull request :)

**Comment by RoboticsYY** [comment]
Thanks. We plan to submit new pull request for the ROS2 porting.

**Pull request closed without merging**
