### PR TITLE
Sync melodic changes to noetic

### PR DESCRIPTION
**Pull request by JeroenDM**

### CODE REVIEW

**Comment by JeroenDM** [comment]
@simonschmeisser do you know of any features in the melodic branch I forgot about?

There is something strange going on in the CI jobs. The same command to install opw-kinematics succeeds in the testing job, but fails in the build job (for melodic). Any idea what could cause this?
```
apt-get install -y -qq ros-melodic-opw-kinematics
```

**Comment by gavanderhoorn** [comment]
`opw_kinematics` has been released, but Melodic hasn't seen a sync yet: [status_page/ros_melodic_default.html?q=opw](http://repositories.ros.org/status_page/ros_melodic_default.html?q=opw).

**Comment by simonschmeisser** [comment]
Looking forward to the sync so github stops sending me red mails each and every morning ...

**Comment by gavanderhoorn** [comment]
It's [been a month](https://discourse.ros.org/c/release/melodic/38), so it would make sense to ask for one again I believe.

**Comment by gavanderhoorn** [comment]
Sync [is out](https://discourse.ros.org/t/new-packages-for-melodic-2021-12-21/23549/1).

**Pull request merged**
